name: Run PHP Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Define the Docker service
      db:
        image: codeinchq/pdf2img:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3000:3000

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP with the version you need
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run tests
      - name: Run tests
        run: vendor/bin/phpunit